honeypots:
  cowrie:
    ports:
      nametelnet: telnet
      protocoltelnet: TCP
      porttelnet: 23
      containerPorttelnet: 2223
    image:
      repository: cowrie_cowrie
      tag: latest
      pullPolicy: IfNotPresent
serviceAccount:
  create: true
  annotations: {}
  name: 
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  extTrafficPolicy: Local
volumes: {}
replicaCount: 2
ingress:
  enabled: false
  className: 
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
imagePullSecrets: []
nameOverride: 
fullnameOverride: 
