apiVersion: v1
kind: Service
metadata:
  name: {{ include "dfsfsd.fullname" .  }}
  labels: {{- include "dfsfsd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.extTrafficPolicy }}
  ports:
    - port: {{ .Values.honeypots.conpot.ports.porthttp }}
      targetPort: {{ .Values.honeypots.conpot.ports.containerPorthttp }}
      protocol: {{ .Values.honeypots.conpot.ports.protocolhttp}}
      name: {{ .Values.honeypots.conpot.ports.namehttp }}
    - port: {{ .Values.honeypots.conpot.ports.portftp }}
      targetPort: {{ .Values.honeypots.conpot.ports.containerPortftp }}
      protocol: {{ .Values.honeypots.conpot.ports.protocolftp}}
      name: {{ .Values.honeypots.conpot.ports.nameftp }}
    - port: {{ .Values.honeypots.conpot.ports.portmodbus }}
      targetPort: {{ .Values.honeypots.conpot.ports.containerPortmodbus }}
      protocol: {{ .Values.honeypots.conpot.ports.protocolmodbus}}
      name: {{ .Values.honeypots.conpot.ports.namemodbus }}
    - port: {{ .Values.honeypots.cowrie.ports.portssh }}
      targetPort: {{ .Values.honeypots.cowrie.ports.containerPortssh }}
      protocol: {{ .Values.honeypots.cowrie.ports.protocolssh}}
      name: {{ .Values.honeypots.cowrie.ports.namessh }}
    - port: {{ .Values.honeypots.cowrie.ports.porttelnet }}
      targetPort: {{ .Values.honeypots.cowrie.ports.containerPorttelnet }}
      protocol: {{ .Values.honeypots.cowrie.ports.protocoltelnet}}
      name: {{ .Values.honeypots.cowrie.ports.nametelnet }}
  selector: {{- include "dfsfsd.selectorLabels" . | nindent 4 }}
