honeypots:
  conpot:
    ports:
      namehttp: http
      protocolhttp: TCP
      porthttp: 80
      containerPorthttp: 80
      nameftp: ftp
      protocolftp: TCP
      portftp: 21
      containerPortftp: 2121
      namemodbus: modbus
      protocolmodbus: TCP
      portmodbus: 502
      containerPortmodbus: 5020
    image:
      repository: ghcr.io/kokol16/conpot
      tag: v2
      pullPolicy: IfNotPresent
  cowrie:
    ports:
      namessh: ssh
      protocolssh: TCP
      portssh: 22
      containerPortssh: 2222
      nametelnet: telnet
      protocoltelnet: TCP
      porttelnet: 23
      containerPorttelnet: 2223
    image:
      repository: cowrie_cowrie
      tag: latest
      pullPolicy: IfNotPresent
serviceAccount:
  create: true
  annotations: {}
  name: 
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  extTrafficPolicy: Local
volumes:
  conpotmountPath: /conpot-json-logs
  conpothostPath: gasdfs
  cowriemountPath: /cowrie/cowrie-git/var/log/cowrie
  cowriehostPath: fsafds
replicaCount: 1
ingress:
  enabled: false
  className: 
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
imagePullSecrets: []
nameOverride: 
fullnameOverride: 
